name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OCAML_VERSION: 4.12.1
  
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3

    - name: Cache OCaml's opam
      uses: actions/cache@v2.1.5
      with:
        path: ~/.opam
        key: ${{matrix.os}}-ocaml-${{env.OCAML_VERSION}}

    - name: Use OCaml ${{env.OCAML_VERSION}}
      uses: ocaml/setup-ocaml@v2.0.3
      with:
        ocaml-compiler: ${{env.OCAML_VERSION}}
        opam-pin: false
        opam-depext: false

    - name: Install dependencies
      run: opam install dune reanalyze

    - name: Build executables
      run: opam exec -- dune build

    - name: Run roundtrip tests
      run: opam exec -- make roundtrip-test
