name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest, macos-arm]
        ocaml_compiler: [4.14.0]

    runs-on: ${{matrix.os}}

    steps:
      - name: "Windows: Set git to use LF"
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Use OCaml ${{matrix.ocaml_compiler}}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{matrix.ocaml_compiler}}
          opam-pin: false
          opam-depext: false

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build executables
        run: opam exec -- dune build

      - name: Run roundtrip tests
        if: runner.os != 'Windows'
        run: opam exec -- make roundtrip-test

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: opam exec -- make test
